### PR TITLE
add stack.yaml with pandoc types 1.17.04 and lts-7.5

### PR DESCRIPTION
**Pull request by rafaqz**
It just needed an update to pandoc types and everything works. I added a stack.yaml file and removed the old cabal.config as that's how I'm used to doing these things.

### CODE REVIEW

**Comment by spwhitton** [comment]
Thank you for working on this, but I don't want to accept a patch that
changes the way the project is built.

I'll use your patch as a basis for my fix, when I have some time for it.

-- 
Sean Whitton

**Comment by rafaqz** [comment]
Sure. But this is the standard build setup all pandoc filters are using now:

https://github.com/lierdakil/pandoc-crossref
https://github.com/jgm/pandoc-citeproc
https://github.com/baig/pandoc-csv2table

I only ever use stack so I have no idea about cabal.conf, but it seems like
overkill to specify that many dependencies for such a small project when
the pandoc-templates version is all that really matters.

I'll maintain a fork, as I can see this happening fairly regularly on arch
if you are waiting for updates on debian.

**Comment by spwhitton** [comment]
Hello,

The cabal.config file I use is just a Stackage snapshot.  So it does
exactly what stack does.  But the package can be built with cabal or
stack.  Relying on stack.yaml means it can only be built with stack.

-- 
Sean Whitton

**Comment by rafaqz** [comment]
Ok that makes sense, just looks pretty confusing in the repo compared to
stack.yaml.

**Pull request closed without merging**
